# Generated by Django 2.2.24 on 2021-12-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
 lesson_15
        ("ordersapp", "0001_orders"),

        ('ordersapp', '0001_orders'),
 master
    ]

    operations = [
        migrations.AlterField(
 lesson_15
            model_name="order",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="активен"),

            model_name='order',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='активен'),
 master
        ),
    ]
