# Generated by Django 2.2.24 on 2021-12-25 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_auto_20211219_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 27, 15, 19, 13, 666379, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
